package interfaces;
import java.sql.Connection;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author monse
 */
public class LogIn extends javax.swing.JFrame {
    private final Connection con;

    
    public LogIn(Connection con) {
        this.con = con;
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Log in");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        showHideButton = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.pink);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 29, 61));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 390));

        jPanel2.setBackground(new java.awt.Color(255, 195, 0));

        jTextField1.setBackground(new java.awt.Color(255, 195, 0));
        jTextField1.setFont(new java.awt.Font("Quicksand Light", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 214, 10)));

        jLabel2.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 31, 54));
        jLabel2.setText("Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 119, 610, -1));

        jPanel4.setBackground(new java.awt.Color(255, 214, 10));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Quicksand Book", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 31, 54));
        jLabel3.setText("Contraseña");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        passwordField.setBackground(new java.awt.Color(255, 214, 10));
        passwordField.setFont(new java.awt.Font("Quicksand Book", 0, 18)); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 195, 0)));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel4.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 20, 270, 30));

        showHideButton.setBackground(new java.awt.Color(0, 31, 54));
        showHideButton.setFont(new java.awt.Font("Quicksand Book", 0, 1)); // NOI18N
        showHideButton.setForeground(new java.awt.Color(0, 31, 54));
        showHideButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vision-baja.png"))); // NOI18N
        showHideButton.setText("Mostrar Contraseña");
        showHideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showHideButtonMouseClicked(evt);
            }
        });
        jPanel4.add(showHideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 40, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 600, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 29, 61));
        jLabel1.setFont(new java.awt.Font("Comfortaa", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 85, 96));
        jLabel1.setText("I N I C I A R  S E S I Ó N");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 60));

        btnAceptar.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 29, 61));
        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        jPanel5.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        btnCerrar.setFont(new java.awt.Font("Comfortaa", 0, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 29, 61));
        btnCerrar.setText("Cerrar");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel5.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 610, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        String usuario = jTextField1.getText().trim();
        String contraseña = new String(passwordField.getPassword()).trim();
        
        if (autenticarUsuario(usuario, contraseña)) {
            this.dispose();
            PaginaPrincipal.setUsuario(usuario);
            new PaginaPrincipal(con).setVisible(true);
        } else {
            mostrarMensajeError("Usuario o contraseña incorrectos.");
        }
    }//GEN-LAST:event_btnAceptarMouseClicked
    
    private boolean autenticarUsuario(String usuario, String contraseña) {
        String sql = "SELECT * FROM admin WHERE usuario = ? AND password = ?";
        
        try (PreparedStatement pstmt = con.prepareStatement(sql)) {
            pstmt.setString(1, usuario);
            pstmt.setString(2, contraseña);
            ResultSet rs = pstmt.executeQuery();
            return rs.next(); // Si hay al menos una fila en el resultado, la autenticación es exitosa.
        } catch (SQLException e) {
            mostrarMensajeError("Error al autenticar usuario: " + e.getMessage());
            return false;
        }
    }

    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void showHideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showHideButtonMouseClicked
        // TODO add your handling code here:
         String buttonText = showHideButton.getText();
        // Cambiar el carácter de ocultamiento según el texto del botón
        if (buttonText.equals("Mostrar Contraseña")) {
            passwordField.setEchoChar((char) 0); // Mostrar la contraseña
            showHideButton.setText("Ocultar Contraseña");
            showHideButton.setIcon(new ImageIcon(getClass().getResource("/imagenes/vision-baja.png")));

        } else {
            passwordField.setEchoChar('*'); // Ocultar la contraseña
            showHideButton.setText("Mostrar Contraseña");
            showHideButton.setIcon(new ImageIcon(getClass().getResource("/imagenes/ojo.png")));
        }
    }//GEN-LAST:event_showHideButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel showHideButton;
    // End of variables declaration//GEN-END:variables
}
