
package interfaces;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author monse
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    private final Connection con;
    static String usuario;
    
    public PaginaPrincipal(Connection con) {
        this.con = con;
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Página Principal");
        this.setResizable(false);
    }
    
    public static void setUsuario(String nombreUsuario) {
        usuario = nombreUsuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAjustes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnMaterialDisponible = new javax.swing.JLabel();
        btnPrestamos = new javax.swing.JPanel();
        Prestamo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDocentes = new javax.swing.JPanel();
        Agregar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnMaterial = new javax.swing.JPanel();
        Eliminar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JPanel();
        Consultar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 29, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ajustes (1).png"))); // NOI18N
        btnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjustesMouseClicked(evt);
            }
        });
        jPanel1.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 614, 65, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setFont(new java.awt.Font("Quicksand Light", 0, 18)); // NOI18N
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (3).png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 170, 30));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1200, 50));

        jPanel3.setBackground(new java.awt.Color(204, 220, 232));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(1, 75, 142));
        jLabel14.setFont(new java.awt.Font("Quicksand Bold", 1, 65)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" B I E N V E N I D A");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Quicksand Book", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ciclo Escolar 2023-2024");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2024-04-12 at 08.53.37.jpeg"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -420, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 1200, 250));

        jPanel4.setBackground(new java.awt.Color(0, 53, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(1, 75, 142));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(1, 75, 142));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 285, 66));

        btnMaterialDisponible.setFont(new java.awt.Font("Quicksand Light", 0, 18)); // NOI18N
        btnMaterialDisponible.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterialDisponible.setText("Ver materiales disponibles");
        btnMaterialDisponible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialDisponibleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMaterialDisponibleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMaterialDisponibleMouseReleased(evt);
            }
        });
        jPanel5.add(btnMaterialDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1100, 66));

        btnPrestamos.setBackground(new java.awt.Color(1, 75, 142));
        btnPrestamos.setPreferredSize(new java.awt.Dimension(260, 260));
        btnPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrestamosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrestamosMouseReleased(evt);
            }
        });
        btnPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Prestamo.setFont(new java.awt.Font("Quicksand Bold", 0, 36)); // NOI18N
        Prestamo.setForeground(new java.awt.Color(255, 255, 255));
        Prestamo.setText("Préstamos");
        btnPrestamos.add(Prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 36, -1, 43));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro-marcador.png"))); // NOI18N
        btnPrestamos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jPanel4.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 115, -1, -1));

        btnDocentes.setBackground(new java.awt.Color(1, 75, 142));
        btnDocentes.setPreferredSize(new java.awt.Dimension(260, 260));
        btnDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocentesMouseClicked(evt);
            }
        });
        btnDocentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar.setFont(new java.awt.Font("Quicksand Bold", 0, 36)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setText("Docentes");
        btnDocentes.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 43));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taller-bnco.png"))); // NOI18N
        btnDocentes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 113, -1, -1));

        jPanel4.add(btnDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 115, -1, -1));

        btnMaterial.setBackground(new java.awt.Color(1, 75, 142));
        btnMaterial.setPreferredSize(new java.awt.Dimension(260, 260));
        btnMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaterialMouseClicked(evt);
            }
        });
        btnMaterial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar.setFont(new java.awt.Font("Quicksand Bold", 0, 36)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Material");
        btnMaterial.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 38, -1, 43));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resaltador-bnco.png"))); // NOI18N
        btnMaterial.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 113, -1, -1));

        jPanel4.add(btnMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 115, -1, -1));

        btnConsultar.setBackground(new java.awt.Color(1, 75, 142));
        btnConsultar.setPreferredSize(new java.awt.Dimension(260, 260));
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        btnConsultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Consultar.setFont(new java.awt.Font("Quicksand Bold", 0, 36)); // NOI18N
        Consultar.setForeground(new java.awt.Color(255, 255, 255));
        Consultar.setText("Consultar");
        btnConsultar.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 43));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar-alt.png"))); // NOI18N
        btnConsultar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 108, -1, -1));

        jPanel4.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 115, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 1200, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        this.dispose();
        new LogIn(con).setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseClicked
        this.dispose();
        new Prestamos(con).setVisible(true);
    }//GEN-LAST:event_btnPrestamosMouseClicked

    private void btnDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocentesMouseClicked
        this.dispose();
        new DocentesI(con).setVisible(true);
    }//GEN-LAST:event_btnDocentesMouseClicked

    private void btnMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialMouseClicked
        this.dispose();
        new MaterialI(con).setVisible(true);
    }//GEN-LAST:event_btnMaterialMouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        this.dispose();
        new Consultar(con).setVisible(true);
        //Consultar ventana = new Consultar(); // Crea una instancia de Ventana2
        //ventana.setVisible(true);
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnMaterialDisponibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialDisponibleMouseClicked
        this.dispose();
        new StockActual(con).setVisible(true);
    }//GEN-LAST:event_btnMaterialDisponibleMouseClicked

    private void btnMaterialDisponibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialDisponibleMousePressed
        btnMaterialDisponible.setForeground(Color.YELLOW);
        
    }//GEN-LAST:event_btnMaterialDisponibleMousePressed

    private void btnMaterialDisponibleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialDisponibleMouseReleased
        btnMaterialDisponible.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMaterialDisponibleMouseReleased

    private void btnPrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestamosMousePressed

    private void btnPrestamosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestamosMouseReleased

    }//GEN-LAST:event_btnPrestamosMouseReleased

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Ajustes(con).setVisible(true);
    }//GEN-LAST:event_btnAjustesMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel Consultar;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Prestamo;
    private javax.swing.JLabel btnAjustes;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JPanel btnConsultar;
    private javax.swing.JPanel btnDocentes;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JPanel btnMaterial;
    private javax.swing.JLabel btnMaterialDisponible;
    private javax.swing.JPanel btnPrestamos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
